name: Update Blog Posts

on:
  push:
    branches:
      - main  # Assuming your default branch is named "main"
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Debug
      run: |
        echo "GH_PAT: ${{ secrets.GH_PAT }}"
        git remote -v
        git branch -a
        git log -1
        cat $HOME/.gitconfig
      
    - name: Push changes
      run: |
         git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/Ga0Kwon/velog.git
         git push origin main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      run: python scripts/update_blog.py

  another_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Another step...
      run: echo "This is another job."

# Add more jobs as needed
